name: Install
on: push
jobs:
  install:
    name: Install on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install Package
      run: pip install git+https://github.com/viral32111/slashcommands
